### ISSUE TITLE
The use-package coloring is disabled after turning on the xah-elisp-mode.

### ISSUE THREAD

**Issue by duzaichuan** [xahlee/xah-elisp-mode#7]
Thanks for this package! Everything seems perfect except that the use-package highlighting disappears. Since I am a beginner, I have to rely on use-package heavily. Any solutions?

**Comment by xahlee** [comment]
what do you mean?? I can't figure out what you mean. The use-package package's code are usually not syntax highlighted as far as i know. Not in emacs lisp mode.

can you show a screenshot? and or the code and tell me in what mode it is colored.

**Comment by duzaichuan** [comment]
Oh, that's weird. I use zenburn theme and have the use-package highlighting and the keywords like :ensure and :config being bold in emacs lisp mode:
<img width="912" alt="image" src="https://user-images.githubusercontent.com/32022901/44615915-7beadf00-a845-11e8-8c89-00fbd1225c30.png">
<img width="832" alt="image" src="https://user-images.githubusercontent.com/32022901/44615936-24993e80-a846-11e8-8598-e4f7bd6fd448.png">

**Comment by xahlee** [comment]
i've made changes (new version is on github) The :name in (:name val) will now be colored like emacs lisp mode.

basically, xah-elisp-mode is designed to color only builtin words. that is, symbol that has special meaning by default. If they are spelled incorrectly, but even in the right form, they should not colored. Those property keys are really not builtin, or rather, hard to define what is meant by builtin, because it depends on which function uses it... but anyone i think it makes good sense to color them.

thanks for the report.

**Comment by duzaichuan** [comment]
Thank you! Your logic makes sense to me. And the changes work nice~
